# https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md
additionalProperties:
  typescriptThreePlus: true
  useTags: true
  allowUnicodeIdentifiers: true
  prefixParameterInterfaces: true
