/* tslint:disable */
/* eslint-disable */
/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * some description
 * @export
 * @interface Amount
 */
export interface Amount {
  /**
   * some description
   * @type {number}
   * @memberof Amount
   */
  value: number;
  /**
   * some description
   * @type {string}
   * @memberof Amount
   */
  currency: string;
}

export function AmountFromJSON(json: any): Amount {
  return AmountFromJSONTyped(json, false);
}

export function AmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Amount {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json['value'],
    currency: json['currency'],
  };
}

export function AmountToJSON(value?: Amount | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value,
    currency: value.currency,
  };
}
