/* tslint:disable */
/* eslint-disable */
/**
 * Library
 * Library example
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Book
 */
export interface Book {
  /**
   *
   * @type {number}
   * @memberof Book
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  author?: string;
  /**
   *
   * @type {boolean}
   * @memberof Book
   */
  available?: boolean;
}

export function BookFromJSON(json: any): Book {
  return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    title: !exists(json, 'title') ? undefined : json['title'],
    author: !exists(json, 'author') ? undefined : json['author'],
    available: !exists(json, 'available') ? undefined : json['available'],
  };
}

export function BookToJSON(value?: Book | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    author: value.author,
    available: value.available,
  };
}
