/* tslint:disable */
/* eslint-disable */
/**
 * Library
 * Library example
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NewBook
 */
export interface NewBook {
  /**
   *
   * @type {string}
   * @memberof NewBook
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof NewBook
   */
  author?: string;
}

export function NewBookFromJSON(json: any): NewBook {
  return NewBookFromJSONTyped(json, false);
}

export function NewBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewBook {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    author: !exists(json, 'author') ? undefined : json['author'],
  };
}

export function NewBookToJSON(value?: NewBook | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    author: value.author,
  };
}
