/* tslint:disable */
/* eslint-disable */
/**
 * Library
 * Library example
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RemovedItem
 */
export interface RemovedItem {
  /**
   *
   * @type {string}
   * @memberof RemovedItem
   */
  removedId?: string;
}

export function RemovedItemFromJSON(json: any): RemovedItem {
  return RemovedItemFromJSONTyped(json, false);
}

export function RemovedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovedItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    removedId: !exists(json, 'removedId') ? undefined : json['removedId'],
  };
}

export function RemovedItemToJSON(value?: RemovedItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    removedId: value.removedId,
  };
}
